#!/bin/bash
#Script Variables
HOST='68.168.220.235';
USER='hitbuild_alinajdev';
PASS='alinajdev@';
DBNAME='hitbuild_alinajdev';
PORT_TCP='1194';
PORT_UDP='110';
PORT_SSL='443';
OBFS='najdev';
HYSTERIA_TYPE='default';
PORT_VLESS='442';
API_LINK='https://alinajdev.com/api/authentication';
API_KEY='@@@PANEL@@@';
DOMAIN=muii.alinajdev.com
NS=tamk.alinajdev.com
404: Not Found